# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nathan Braswell (Limvot)
tagline:          Github Homepage 
url:              https://github.com/Limvot
paginate:         1
baseurl:          /
author:
  name:           Nathan Braswell
  url:            http://limvot.github.io/
  email:          miloignis@gmail.com 

# Custom vars
version:          0.0.0
github:
